### ISSUE TITLE
Handling Key Updates by both Peers

### ISSUE THREAD

**Issue by hannestschofenig** [hannestschofenig/tls-key-update#2]
> If implementations independently initiate the extended key update procedure, and they cross in flight, the result is that each side increments keys by two generations.

comment> Another way to handle the race condition is that ExtendedKeyUpdateRequest which has lower lexicographic order will be discarded by the TLS peer. This approach ensures that only one key update is processed, avoiding the need to compute the keys twice and thereby simplifying the process.

Alternatively, a default policy where the server has a higher precedence and in case of a race condition the ExtendedKeyUpdateRequest from the client would be discarded.

**Comment by stfries** [comment]
I would be in favor with the alternative as it also aligns with the cipher suite negotiation. Here also the server has the last word in the selection.
